config/routes.rb
Rails.application.routes.draw do
  resources :members

  root 'members#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
    validates_presence_of :title, :release
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Movie was successfully added.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Movie was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:title, :release)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movies To See</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class='container'>
    <%= yield %>
    </div>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-inline">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label 'Release Date' %>
      <%= f.text_field :release, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-default' %>
    </div>
  </form>
  
  <% end %>

app/views/members/edit.html.erb
<h1>Edit Movie Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Movies To See</title>
</head>
<body>
<div class="form-group">
  <div class="well">
      <h1>Movies to See:</h1>
  </div>
        
  <table class="table table-responsive table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Release Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.title %></td>
          <td><%= member.release %></td>
          <td><%= link_to 'View', member %></td>
          <td><%= link_to 'Edit', edit_member_path(member) %></td>
          <td><%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  
  <br>
  
  <%= link_to 'Add New Movie', new_member_path, class: 'btn btn-default' %>
  
  </div>
</body>
</html>

app/views/members/new.html.erb
 
<h1>Add New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

</html>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @member.title %></h1>
</p>

<p>
  <strong>Release Date:</strong>
  <%= @member.release %>
</p>

<p>
  <strong>Description:</strong>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

</html>